octoprint:
  host: 192.168.13.158 #prusamk3.local
  name: prusamk3
  api_key: !secret octo_api_prusa
  bed: True
  number_of_tools: 1

sensor:
  - platform: octoprint
    name: Prusa OctoPrint

binary_sensor:
  - platform: octoprint
    name: Prusa OctoPrint

camera:
  - platform: mjpeg
    name: PrusaCam
    mjpeg_url: http://192.168.13.158/webcam/?action=stream
    still_image_url: http://192.168.13.158/webcam/?action=snapshot
