homeassistant:
  customize:
    sensor.us_air_quality_index:
      friendly_name: Air Quality Index
    sensor.us_air_pollution_level:
      friendly_name: Air Pollution Level
    sensor.us_main_pollutant:
      friendly_name: Main Pollutant

sensor:
  - platform: airvisual
    api_key: !secret airvisual_key
    monitored_conditions:
      - us
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 500
    show_on_map: false

group:
  air_quality_home_card:
    view: no
    name: Air Quality
    entities:
      - sensor.us_air_quality_index
      - sensor.us_air_pollution_level
      - sensor.us_main_pollutant
    
