sensor:
  - platform: airvisual
    api_key: !secret airvisual_key
    monitored_conditions:
      - us
      - cn
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 500
    show_on_map: false

group:
  air_quality_home_card:
    view: no
    name: Air Quality
    entities:
      - sensor.us_air_quality_index
      - sensor.us_air_pollution_level
      - sensor.us_main_pollutant
      - sensor.chinese_air_quality_index
      - sensor.chinese_air_pollution_level
      - sensor.chinese_main_pollutant
    
