homeassistant:
  customize:
    script.backroom_light_day:
      hidden: true
    script.backroom_light_night:
      hidden: true
    light.back_ceiling:
      friendly_name: Back Room Light
    binary_sensor.back_door_hal_sensor:
      friendly_name: Back Room Door
    sensor.back_door_hal_temperature:
      friendly_name: Back Room Temperature

group:
  backroom_room:
    name: Back Room
    entities:
      - light.back_ceiling
      - binary_sensor.back_door_hal_sensor
      - sensor.back_door_hal_temperature

binary_sensor:
  - platform: template
    sensors:
      back_door_hal_sensor:
        device_class: opening
        value_template: >-
          {%- if is_state('sensor.back_door_hal_access_control', '22') -%}
          true
          {%- else -%}
          false
          {%- endif -%}

automation:
  - alias: Back Room - door opens
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door_hal_sensor
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.backroom_light_turn_on

  - alias: Back Room - door opens
    trigger:
      - platform: state
        entity_id: binary_sensor.back_door_hal_sensor
        to: 'off'
    action:
      - service: script.turn_on
        entity_id: script.backroom_light_turn_off

script:
  backroom_light_turn_off:
    alias: Back Room - light turn off
    sequence:
      - service: light.turn_off
        entity_id: light.back_ceiling

  backroom_light_turn_on:
    alias: Back Room - light turn on
    sequence:
      - service: script.turn_on
        entity_id:
          - script.backroom_light_morning
          - script.backroom_light_evening
          - script.backroom_light_sleep

  backroom_light_morning:
    sequence:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: disarmed
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - service: light.turn_on
        data:
          entity_id: light.back_ceiling
          brightness_pct: 100
          color_temp: 150
          transition: 3

  backroom_light_evening:
    sequence:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: disarmed
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - service: light.turn_on
        data:
          entity_id: light.back_ceiling
          brightness_pct: 100
          color_temp: 500
          transition: 3

  backroom_light_sleep:
    sequence:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_night
      - service: light.turn_on
        data:
          entity_id: light.back_ceiling
          brightness_pct: 20
          color_temp: 500
          transition: 15
