homeassistant:
  customize:
    group.bedroom:
      order: 2
    script.mbr_light_evening:
      hidden: true
    script.mbr_light_sleep:
      hidden: true
    script.mbr_morning_wake_up:
      can_cancel: false
      homebridge_visible: true
    script.mbr_morning_wake_up_end:
      can_cancel: false
      homebridge_visible: true
    light.mbr_ceiling:
      friendly_name: Bedroom Ceiling Light
    light.mbr_floor:
      friendly_name: Bedroom Floor Light
    binary_sensor.mbr_pir_sensor:
      device_class: motion
      friendly_name: Bedroom Motion
    sensor.mbr_pir_temperature:
      friendly_name: Bedroom Temperature
    sensor.mbr_pir_luminance:
      friendly_name: Bedroom Luminance
    sensor.mbr_smoke_temperature:
      friendly_name: Bedroom Temperature (SA)

group:
  bedroom:
    name: Bedroom
    icon: mdi:hotel
    view: yes
    entities:
      - group.mbr_card
      - group.mbr_alarm_clock_card
      - binary_sensor.mbr_smoke_sensor
      - binary_sensor.mbr_pir_sensor

  mbr_card:
    name: Master Bedroom
    view: no
    entities:
      - light.mbr_ceiling
      - light.mbr_floor
      #- sensor.mbr_smoke_temperature
      - sensor.mbr_pir_temperature
      #- sensor.mbr_pir_luminance

  mbr_alarm_clock_card:
    name: Bedroom Alarm Clock
    view: no
    entities:
      - input_select.mbr_tune
      - script.mbr_morning_wake_up
      - script.mbr_morning_wake_up_end
      - automation.mbr_motion
      - automation.mbr_no_motion

input_select:
  mbr_tune:
    name: Bedroom Tune
    options:
      - Fresh Electronic
      - Wake Up Happy
      - None
    initial: None
    icon: mdi:speaker

automation:
  - id: mbr_motion
    alias: Bedroom - motion
    trigger:
      - platform: state
        entity_id: binary_sensor.mbr_pir_sensor
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.mbr_light_turn_on

  - id: mbr_no_motion
    alias: Bedroom - no motion
    trigger:
      - platform: state
        entity_id: binary_sensor.mbr_pir_sensor
        to: 'off'
    action:
      - service: script.turn_on
        entity_id: script.mbr_light_turn_off

  - id: mbr_wake_up_end
    alias: Bedroom - Wakeup End
    trigger: 
      - platform: state
        entity_id: alarm_control_panel.alarm
        from: armed_night
        to: disarmed
    action:
      - service: script.turn_on
        entity_id: script.mbr_morning_wake_up_end

  - id: mbr_wake_up
    alias: Bedroom - WakeUp
    trigger:
      - platform: time
        hours: 8
        minutes: 30
        seconds: 00
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_night
    action:
      - service: script.turn_on
        entity_id: script.mbr_morning_wake_up

  - id: mbr_tune_stop
    trigger:
      - platform: state
        entity_id: input_select.mbr_tune
        to: "None"
    action:
      - service: media_player.media_stop
        entity_id: media_player.bedroom

script:
  mbr_morning_wake_up:
    alias: Bedroom - Morning Wakeup
    sequence:
      - service: automation.turn_off
        entity_id: 
          - automation.bedroom__no_motion
          - automation.bedroom__motion
      - service: light.turn_on
        data:
          entity_id: light.mbr_ceiling
          brightness_pct: 100
          color_temp: 150
          transition: 60
      - service: script.sonos_say
        data:
          sonos_entity: media_player.bedroom
          volume: 0.3
          message: 'Good Morning!'
          delay: '00:00:03'
      - delay: '00:00:05'
      - service: script.sonos_say
        data:
          sonos_entity: media_player.bedroom
          volume: 0.3
          message: 'Time to wake up.'
          delay: '00:00:02'
      - delay: '00:00:03'
#      - condition: state
#        entity_id: alarm_control_panel.alarm
#        state: armed_night
      - service: script.turn_on
        entity_id: script.sonos_play_morning

  mbr_morning_wake_up_end:
    alias: Bedroom - Cancel Wakeup
    sequence:
      - service: media_player.media_stop
        entity_id: media_player.bedroom
      - service: light.turn_off
        entity_id: light.mbr_ceiling
      - service: automation.turn_on
        entity_id: 
          - automation.bedroom__no_motion
          - automation.bedroom__motion

  mbr_light_turn_off:
    alias: Bedroom - turn off lights
    sequence:
      - service: light.turn_off
        entity_id:
          - light.mbr_ceiling
          - light.mbr_floor

  mbr_light_turn_on:
    alias: Bedroom - turn on lights
    sequence:
      - service: script.turn_on
        entity_id: 
          - script.mbr_light_morning
          - script.mbr_light_evening
          - script.mbr_light_sleep

  mbr_light_morning:
    sequence:
      - condition: or
        conditions:
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: pending
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - service: light.turn_on
        data:
          entity_id: 
            - light.mbr_ceiling
            - light.mbr_floor
          brightness_pct: 100
          color_temp: 150
          transition: 3

  mbr_light_evening:
    sequence:
      - condition: or
        conditions:
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: disarmed
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: pending
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - service: light.turn_on
        data:
          entity_id:
            - light.mbr_ceiling
            - light.mbr_floor
          brightness_pct: 100
          color_temp: 500
          transition: 3

  mbr_light_sleep:
    sequence:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_night
      - service: light.turn_on
        data:
          entity_id:
            #- light.mbr_ceiling
            - light.mbr_floor
          brightness_pct: 20
          color_temp: 500
          transition: 15
