homeassistant:
  customize:
    device_tracker.unifi:
      hidden: false

device_tracker:
- platform: unifi
  host: !secret unifi_host
  port: 443
  username: !secret unifi_username
  password: !secret unifi_password
  site_id: !secret unifi_site_id 
  verify_ssl: true
  new_device_defaults:
    track_new_devices: false
