homeassistant:
  customize:
    sensor.ha_version:
      friendly_name: New Release
    script.update_home_assistant_home:
      friendly_name: Home Assistant Update
      icon: mdi:update
    sensor.hass_uptime:
      friendly_name: Home Assistant Uptime
      icon: mdi:home-assistant


group:
  homeass_version_card:
   name: Home Assistant Info
   entities:
     - sensor.ha_version
     - sensor.installed_version
     - input_select.log_level

sensor:
  ###### VERSIONS
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current Version
  - platform: command_line
    command: python3 -c "import homeassistant.const as ha;print('{}.{}.{}'.format(ha.MAJOR_VERSION, ha.MINOR_VERSION, ha.PATCH_VERSION))"
    name: Installed Version

  - platform: template
    sensors:
      ha_version:
        value_template: >-
          {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
            {{ states('sensor.installed_version') }}
          {% else %}
            {{ states('sensor.current_version') }} Available
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}
