homeassistant:
  customize:

light:
  - platform: group
    name: Hangar 55
    entities:
      - light.back_ceiling
      - light.back_bench

binary_sensor:
  - platform: template
    sensors:
      back_door_hal_sensor:
        device_class: door
        value_template: >-
          {%- if is_state('sensor.back_door_hal_access_control', '22') -%}
          true
          {%- else -%}
          false
          {%- endif -%}

#automation:
#  - alias: Back Room - door opens
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.back_door_hal_sensor
#        to: 'on'
#    action:
#      - service: script.turn_on
#        entity_id: script.backroom_light_turn_on

#  - alias: Back Room - door closes
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.back_door_hal_sensor
#        to: 'off'
#    action:
#      - service: script.turn_on
#        entity_id: script.backroom_light_turn_off

#script:
#  backroom_light_turn_off:
#    alias: Back Room - light turn off
#    sequence:
#      - service: light.turn_off
#        entity_id: 
#          - light.back_ceiling
#          - light.back_bench
#
#  backroom_light_turn_on:
#    alias: Back Room - light turn on
#    sequence:
#      - service: script.turn_on
#        entity_id:
#          - script.backroom_light_morning
#          - script.backroom_light_evening
#          - script.backroom_light_sleep

#  backroom_light_morning:
#    sequence:
#      - condition: or
#        conditions:
#        - condition: state
#          entity_id: alarm_control_panel.alarm
#          state: disarmed
#        - condition: state
#          entity_id: alarm_control_panel.alarm
#          state: pending
#      - condition: state
#        entity_id: sun.sun
#        state: 'above_horizon'
#      - service: light.turn_on
#        data:
#          entity_id: 
#            - light.back_ceiling
#            - light.back_bench
#          brightness_pct: 100
#          color_temp: 150
#          transition: 3

#  backroom_light_evening:
#    sequence:
#      - condition: or
#        conditions:
#        - condition: state
#          entity_id: alarm_control_panel.alarm
#          state: disarmed
#        - condition: state
#          entity_id: alarm_control_panel.alarm
#          state: pending
#      - condition: state
#        entity_id: sun.sun
#        state: 'below_horizon'
#      - service: light.turn_on
#        data:
#          entity_id: 
#            - light.back_ceiling
#            - light.back_bench
#          brightness_pct: 100
#          color_temp: 500
#          transition: 3
#
#  backroom_light_sleep:
#    sequence:
#      - condition: state
#        entity_id: alarm_control_panel.alarm
#        state: armed_night
#      - service: light.turn_on
#        data:
#          entity_id:
#            - light.back_ceiling
#            - light.back_bench
#          brightness_pct: 20
#          color_temp: 500
#          transition: 15
