input_select:
  lr_scenes:
    name: Livingroom Scene
    options:
      - Aziz
      - Daytime
      - Evening
      - TV
      - PC Gaming
      - Pink
      - Red

automation:
  - alias: Livingroom Scene Aziz
    trigger:
      platform: state
      entity_id: input_select.lr_scenes
      to: "Aziz"
    action:
      service: scene.turn_on
      entity_id: scene.aziz
  - alias: Livingroom Scene Daytime
    trigger:
      platform: state
      entity_id: input_select.lr_scenes
      to: "Daytime"
    action:
      service: scene.turn_on
      entity_id: scene.daytime
  - alias: Livingroom Scene Evening
    trigger:
      platform: state
      entity_id: input_select.lr_scenes
      to: "Evening"
    action:
      service: scene.turn_on
      entity_id: scene.evening
  - alias: Livingroom Scene PC Gaming
    trigger:
      platform: state
      entity_id: input_select.lr_scenes
      to: "PC Gaming"
    action:
      service: scene.turn_on
      entity_id: scene.pc_gaming
  - alias: Livingroom Scene TV
    trigger:
      platform: state
      entity_id: input_select.lr_scenes
      to: "TV"
    action:
      service: scene.turn_on
      entity_id: scene.tv
  - alias: Livingroom Scene Pink
    trigger:
      platform: state
      entity_id: input_select.lr_scenes
      to: "Pink"
    action:
      service: scene.turn_on
      entity_id: scene.pink
  - alias: Livingroom Scene Red
    trigger:
      platform: state
      entity_id: input_select.lr_scenes
      to: "Red"
    action:
      service: scene.turn_on
      entity_id: scene.red
      
scene:
  - name: Aziz
    entities:
      input_select.lr_scenes:
        option: Aziz
      group.lr_color_lights:
        state: on
        brightness_pct: 100
        color_temp: 150
      light.lr_media_strip:
        state: off
  - name: Daytime
    entities:
      input_select.lr_scenes:
        option: Daytime
      light.tv_backlight:
        state: off
      light.lr_pod_right:
        state: on
        brightness_pct: 100
        color_temp: 150
      light.lr_tower_right:
        state: on
        brightness_pct: 100
        color_temp: 150
      light.lr_tower_left:
        state: on
        brightness_pct: 100
        color_temp: 150
      light.lr_message:
        state: on
        brightness_pct: 70
        color_temp: 150
      light.lr_ceiling:
        state: on
        brightness_pct: 100
        color_temp: 500
        effect: colorloop
      light.lr_tvtable:
        state: off

  - name: Evening
    entities:
      input_select.lr_scenes:
        option: Evening
      light.tv_backlight:
        state: on
        brightness_pct: 70
        color_temp: 500
      light.lr_pod_right:
        state: on
        brightness_pct: 100
        color_temp: 500
      light.lr_tower_right:
        state: on
        brightness_pct: 100
        color_temp: 500
      light.lr_tower_left:
        state: on
        brightness_pct: 100
        color_temp: 500
      light.lr_message:
        state: on
        brightness_pct: 70
        color_temp: 500
      light.lr_ceiling:
        state: on
        brightness_pct: 100
        color_temp: 500
        effect: colorloop
      light.hall:
        state: on
        brightness_pct: 40
        color_temp: 500
      light.lr_tvtable:
        state: on
        brightness_pct: 100
        rgb_color: [255, 127, 0]

  - name: TV
    entities:
      input_select.lr_scenes:
        option: TV
      light.tv_backlight:
        state: on
        brightness_pct: 50
        color_temp: 500
      light.lr_tower_right:
        state: on
        brightness_pct: 60
        color_temp: 500
      light.lr_tower_left:
        state: on
        brightness_pct: 60
        color_temp: 500
      light.lr_ceiling:
        state: off
      light.lr_message:
        state: off
      light.lr_pod_right:
        state: on
        brightness_pct: 30
        color_temp: 500
      light.hall:
        state: on
        brightness_pct: 20
        color_temp: 500
      light.lr_tvtable:
        state: on
        brightness_pct: 30
        color_name: 'darkorange'

  - name: PC Gaming
    entities: 
      input_select.lr_scenes:
        option: PC Gaming
      light.tv_backlight:
        state: on
        brightness_pct: 70
        color_name: 'darkorange'
      light.lr_message:
        state: off
      light.lr_tower_right:
        state: on
        brightness_pct: 100
        color_name: 'darkorange'
      light.lr_tower_left:
        state: on
        brightness_pct: 100
        color_name: 'darkorange'
      light.lr_pod_right:
        state: on
        brightness_pct: 100
        color_name: 'darkorange'
      light.lr_ceiling:
        state: on
        brightness_pct: 30
        color_temp: 500
        effect: colorloop
      light.hall:
        state: on
        brightness_pct: 40
        color_temp: 500
      light.lr_tvtable:
        state: on
        brightness_pct: 100
        color_name: 'darkorange'

  - name: Pink
    entities: 
      input_select.lr_scenes:
        option: Pink
      light.tv_backlight:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 145]
      light.lr_message:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 145]
      light.lr_tower_right:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 145]
      light.lr_tower_left:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 145]
      light.lr_ceiling:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 145]
      light.lr_pod_right:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 145]
      light.lr_tvtable:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 145]

  - name: Red
    entities: 
      input_select.lr_scenes:
        option: Red
      light.tv_backlight:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_message:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_tower_right:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_tower_left:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_ceiling:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_pod_right:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_tvtable:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]

  - name: xmas
    entities: 
      input_select.lr_scenes:
        option: xmas
      light.tv_backlight:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_message:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_tower_right:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_tower_left:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_ceiling:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_pod_right:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
      light.lr_tvtable:
        state: on
        brightness_pct: 100
        rgb_color: [255, 0, 0]
