homeassistant:
  customize:
#    binary_sensor.lr_smoke_sensor:
#      device_class: smoke
#    binary_sensor.lr_pir_sensor:
#      device_class: motion
#    sensor.lr_pir_relative_humidity:
#      device_class: humidity
#    sensor.lr_pir_temperature:
#      device_class: temperature
#    sensor.lr_pir_luminance:
#      device_class: luminance
#    sensor.climate_pwr_power:
#      device_class: power
#    sensor.lr_media_pwr_power:
#      device_class: power
#    sensor.lr_desk_pwr_power:
#      device_class: power
#    sensor.lr_desk_speakers_pwr_power:
#      device_class: power

light:
  - platform: group
    name: Livingroom Lights
    entities:
      - light.lr_message
      - light.lr_tower_left
      - light.lr_tower_right
      - light.lr_pod_right
      - light.lr_tvtable

  - platform: group
    name: TV Backlight
    entities:
      - light.lr_media_left
      - light.lr_media_strip
      - light.lr_media_right

  - platform: group
    name: Livingroom Color Lights
    entities:
      - light.tv_backlight
      - light.livingroom_lights
      - light.lr_ceiling

#group:
#  livingroom:
#    name: Living Room
#    icon: mdi:youtube-tv
#    view: yes
#    entities:
#      - light.livingroom_lights
#      - binary_sensor.lr_smoke_sensor
#      - binary_sensor.lr_pir_sensor
#      - group.lr_sensors
#      - group.lr_power
#      - climate.livingroom_spaceheater

#  lr_lights:
#    name: Lights
#    view: no
#    entities:
#      - light.lr_ceiling
#      - light.tv_backlight
#      - light.livingroom_lights      

#  lr_power:
#    name: Livingroom Power
#    view: no
#    entities:
#      #- switch.lr_media_pwr_switch
#      - sensor.lr_media_pwr_power
#      - sensor.lr_media_pwr_energy
#      - switch.lr_desk_pwr_switch
#      - sensor.lr_desk_pwr_power
#      - sensor.lr_desk_pwr_energy
#      - switch.lr_desk_speakers_pwr_switch
#      - sensor.lr_desk_speakers_pwr_power
#      - sensor.lr_desk_speakers_pwr_energy
#      - switch.lr_heater_pwr_switch
#      - sensor.lr_heater_pwr_power
#      - sensor.lr_heater_pwr_energy

#  lr_sensors:
#    name: Livingroom Sensors
#    view: no
#    entities:
#      - climate.livingroom_spaceheater
#      #- binary_sensor.lr_pir_sensor
#      #- sensor.lr_smoke_temperature
#      #- sensor.lr_pir_burglar
#      - sensor.lr_pir_relative_humidity
#      - sensor.lr_pir_temperature
#      - sensor.lr_pir_luminance
#      #- sensor.lr_pir_ultraviolet

climate:
#  - platform: generic_thermostat
#    name: Livingroom Climate
#    heater: switch.climate_pwr_switch
#    target_sensor: sensor.lr_pir_temperature
#    min_temp: 18
#    max_temp: 29
#    target_temp: 24
#    cold_tolerance: 0.5
#    keep_alive:
#      minutes: 15

  - platform: generic_thermostat
    name: Livingroom
    heater: switch.climate_pwr_switch
    ac_mode: true
    target_sensor: sensor.lr_pir_temperature
    initial_operation_mode: auto
    cold_tolerance: 1
    hot_tolerance: 1
    min_temp: 19
    max_temp: 26
    target_temp: 24
    keep_alive:
      minutes: 1

#automation:
#  - alias: Livingroom - warmer than 24C
#    trigger: 
#      - platform: numeric_state
#        entity_id: sensor.lr_pir_temperature
#        above: 24.0
#    action:
#      service: switch.turn_off
#      entity_id: switch.lr_heater_pwr_switch

#  - alias: Livingroom - colder than 23.5C
#    trigger:
#      - platform: numeric_state
#        entity_id: sensor.lr_pir_temperature
#        below: 23.5
#    action:
#      service: switch.turn_on
#      entity_id: script.lr_heater_turn_on

script:
  lr_power_down:
    alias: Livingroom - power down
    sequence:
      - service: switch.turn_off
        entity_id:
          - switch.climate_pwr_switch
          - switch.lr_desk_pwr_switch
          - switch.lr_desk_speakers_pwr_switch
      - service: script.turn_on
        entity_id: script.lr_light_turn_off
      - service: climate.turn_off
        entity_id: climate.livingroom
#        data:
#          operation_mode: "off"

  lr_wake_up:
    alias: Livingroom - power up
    sequence:
      - service: script.turn_on
        entity_id: script.lr_light_turn_on
      - service: switch.turn_on
        entity_id:
          - switch.lr_desk_pwr_switch
          - switch.lr_desk_speakers_pwr_switch
      - service: climate.turn_on
        entity_id: climate.livingroom
#        data:
#          operation_mode: "auto"

#  lr_heater_turn_on:
#    alias: Livingroom - heater
#    sequence:
#      - condition: numeric_state
#        entity_id: sensor.lr_pir_temperature
#        below: 24.0
#      - condition: state
#        entity_id: alarm_control_panel.alarm
#        state: disarmed
#      - service: switch.turn_on
#        entity_id:
#          - switch.lr_heater_pwr_switch

  lr_light_turn_off:
    alias: Livingroom - lights turn off
    sequence:
      - service: light.turn_off
        entity_id: group.lr_lights

  lr_light_turn_on:
    alias: Livingroom - lights turn on
    sequence:
      - service: script.turn_on
        entity_id: script.lr_light_day
      - service: script.turn_on
        entity_id: script.lr_light_night

  lr_light_day:
    sequence:
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - service: scene.turn_on
        entity_id: scene.daytime 

  lr_light_night:
    sequence:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - service: scene.turn_on
        entity_id: scene.evening
