homeassistant:
  customize:
    group.rooms:
      order: 4

group:
  rooms:
    name: rooms
    icon: mdi:sort-variant
    view: yes
    entities:
      - group.foyer
      - group.wc_room
      - group.storage
      - group.kitchen
      - group.hall_room
