homeassistant:
  customize:
    sensor.season:
      friendly_name: season
      icon: mdi:calendar-clock

group:
  season_card:
   name: Season
   entities:
     - sensor.season


sensor:
  - platform: season
    type: astronomical

automation:
  - alias: Season Change Notification
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: sensor.season
    condition:
      - condition: template
        value_template: '{{ trigger.from_state.state | lower != "unknown" }}'
    action:
      - service: notify.cnf
        data_template:
          title: "Seasons be changin'"
          message: >
            {%- if trigger is not none %}
            Good bye {{ trigger.from_state.state }}!, and Say Hello to {{ trigger.to_state.state }}.
            {%- endif %}
