#homeassistant:
#  customize:
#    binary_sensor.storage_door_hal_sensor:
#      device_class: door
#    binary_sensor.storage_door_hal_sensor_2:
#      device_class: door

binary_sensor:
  - platform: template
    sensors: 
      storage_door_hal_sensor:
        friendly_name: "Storage Door"
        device_class: door
        value_template: >- 
          {%- if is_state('sensor.storage_door_hal_access_control', '22') -%}
          true
          {%- else -%}
          false
          {%- endif -%}
