homeassistant:
  customize:
#    group.transport:
#      order: 6
    sensor.veloantwerpen_73d91e4b9e877126ab596a46d5cff60d:
      friendly_name: Velo AZ Monica 

#group:
#  transport:
#    icon: mdi:subway-variant
#    view: no
#    entities:
#      - sensor.veloantwerpen_73d91e4b9e877126ab596a46d5cff60d

sensor:
  - platform: citybikes
    stations:
    - 245
