#homeassistant:
#  customize:
#    binary_sensor.wc_door_hal_sensor:
#      device_class: door
#    binary_sensor.wc_pir_sensor:
#      device_class: motion
#    sensor.wc_pir_temperature:
#    sensor.wc_pir_luminance:
#    sensor.wc_door_hal_access_control:
#    sensor.wc_pir_burglar:

binary_sensor:
  - platform: template
    sensors: 
      wc_door_hal_sensor:
        device_class: door
        value_template: >- 
          {%- if is_state('sensor.wc_door_hal_access_control', '22') -%}
          true
          {%- else -%}
          false
          {%- endif -%}

#automation:
#  - alias: WC - motion
#    initial_state: false
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.wc_pir_sensor
#        to: 'on'
#      - platform: state
#        entity_id: binary_sensor.wc_door_hal_sensor
#        to: 'on'
#    action:
#      - service: script.turn_on
#        entity_id: script.wc_light_turn_on

#  - alias: WC - no motion
#    initial_state: false
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.wc_pir_sensor
#        to: 'off'
#        for:
#          minutes: 3
#    action:
#      - service: script.turn_on
#        entity_id: script.wc_light_turn_off

#script:
#  wc_light_turn_off:
#    alias: WC - light turn off
#    sequence:
#      - service: light.turn_off
#        entity_id: light.wc

#  wc_light_turn_on:
#    alias: WC - light turn on
#    sequence:
#      - service: script.turn_on
#        entity_id:
#          - script.wc_light_day
#          - script.wc_light_night

#  wc_light_day:
#    sequence:
#      - condition: or
#        conditions:
#        - condition: state
#          entity_id: alarm_control_panel.alarm
#          state: disarmed
#        - condition: state
#          entity_id: alarm_control_panel.alarm
#          state: pending
#      - service: light.turn_on
#        data:
#          entity_id: light.wc
#          brightness_pct: 80

#  wc_light_night:
#    sequence:
#      - condition: state
#        entity_id: alarm_control_panel.alarm
#        state: armed_night
#      - service: light.turn_on
#        data:
#          entity_id: light.wc
#          brightness_pct: 30
#          transition: 30
